name: "Container Structure Test"
description: "Setup Container Structure Test in your GitHub workflows"
author: "Jeremy Combs"

inputs:
  image:
    description: "Image (including :tag) to test"
  config:
    description: "Path (relative to the root of the repository) to the test config"
  platform:
    description: "Platform to test the image on"
    default: "linux/amd64"
branding:
  icon: "check-circle"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - container-structure-test
    - test
    - --image
    - ${{ inputs.image }}
    - --config
    - ${{ inputs.config }}
    - --platform
    - ${{ inputs.platform }}
